name: Bundle Update (shared)
description: Run bundle update
author: Faculty Development Team

inputs:
  arguments:
    description: Arguments to pass to `bundle update`
    required: false
    default: ""
  checkout-key:
    description: Key to use when checking out the repository
    required: true
  container:
    description: Run in a container (don't run setup-ruby)
    required: true
  working-directory:
    description: Working directory for bundle update
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ inputs.checkout-key }}
    - uses: ruby/setup-ruby@v1
      if: ${{ inputs.container == 'false' }}
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    - run: bundle config --local deployment false
      if: ${{ inputs.container == 'false' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: bundle update ${{ inputs.arguments }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
