name: Bundle Install Deploy
description: Run bundle install command for deployment to AWS
author: Workflow Improvement Team

inputs:
  bundle-clean:
    description: Wherever or not to run "bundle clean" after "bundle install"
    required: false
    default: true
  bundle-without:
    description: Colon-separated list of Gem groups not to install
    required: false
    default: test:development

runs:
  using: composite
  steps:
    - uses: university-of-york/faculty-dev-actions/ruby-3.2-command@v1
      with:
        command: bundle config set deployment true without ${{ inputs.without-gem-groups }} clean ${{ inputs.bundle- }} && bundle install
