name: Build Vue components
description: Build Vue components
author: Faculty Development Team

inputs:
  node-version:
    description: Version of node to use
    required: false
    default: '14'
  working-directory:
    description: Working directory for npm update
    required: false
    default: ./

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ inputs.working-directory }}
    - run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: npx webpack --config webpack.prod.js
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - uses: actions/upload-artifact@v2
      with:
        name: vue-components
        path: ${{ inputs.working-directory }}public/js/**
