name: rspec in Lambda with Vue
description: Run rspec within a lambda container and download vue components
author: Faculty Development Team

inputs:
  artifact-name:
    description: Name for the artifact to download
    required: false
    default: vue-components

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - run: bundle install --deployment --without development
      shell: bash
    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact-name }}
        path: public/js
    - name: RSpec tests
      uses: docker://ghcr.io/university-of-york/faculty-dev-docker-images/ci/aws-lambda-ruby-postgres:2.7
      with:
        args: bundle exec rspec
