name: Bundle Install
description: Run bundle install command
author: Workflow Improvement Team

inputs:
  bundle-clean:
    description: Whether or not to run "bundle clean" after "bundle install"
    required: false
    default: true
  bundle-deployment:
    description: Whether or not to run bundle install in "deployment" mode
    required: false
    default: true
  bundle-without:
    description: Colon-separated list of Gem groups not to install
    required: false
    default: test:development
  ruby-version:
    description: The major & minor-point Ruby version to use, e.g. '3.4' for Ruby 3.4
    required: false
    default: '3.2'

runs:
  using: composite
  steps:
    - name: Bundle update with Ruby 3.2
      if: ${{ inputs.ruby-version == '3.2' }}
      uses: university-of-york/faculty-dev-actions/ruby-3.2-command@v1
      with:
        command: bundle config set deployment ${{ inputs.bundle-deployment }} && bundle config set without ${{ inputs.bundle-without }} && bundle config set clean ${{ inputs.bundle-clean }} && bundle install

    - name: Bundle update with Ruby 3.4
      if: ${{ inputs.ruby-version == '3.4' }}
      uses: university-of-york/faculty-dev-actions/ruby-3.4-command@v1
      with:
        command: bundle config set deployment ${{ inputs.bundle-deployment }} && bundle config set without ${{ inputs.bundle-without }} && bundle config set clean ${{ inputs.bundle-clean }} && bundle install
