name: Bundle Update [development, test] (on a runner)
description: Run bundle update --group test development on a runner; create a PR for any updates; and set the PR to auto-merge
author: Faculty Development Team

inputs:
  checkout-key:
    description: Key to use when checking out the repository
    required: true
  github-token:
    description: GITHUB_TOKEN for setting the PR to auto merge
    required: true
  working-directory:
    description: Working directory for bundle update
    required: false
    default: ./

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ inputs.checkout-key }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    - run: bundle config --local deployment false
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: bundle update --group test development
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        body: Changes after running `bundle update --group test development`
        branch: bundle-update-dev
        commit-message: bundle update --group test development
        delete-branch: true
        labels: dependencies, ruby
        title: Bundle Update [development, test]
    - name: Enable auto-merge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      run: gh pr merge --auto --merge "$PR_URL"
      shell: bash
      env:
        PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
