name: Rubocop
description: Run Rubocop against a repository
author: Faculty Development Team

inputs:
  working-directory:
    description: Working directory for Gemfile
    required: false
    default: ./

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    - run: bundle exec rubocop
      shell: bash
      working-directory: ${{ inputs.working-directory }}
