name: Rubocop
description: Run Rubocop against a repository
author: Faculty Development Team

inputs:
  working-directory:
    description: Working directory for Gemfile
    required: false
    default: ./

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    - run: |
        RUBOCOP_VERSION=`bundle exec rubocop -v`
        MARKDOWN=`ruby -e "p Gem::Version.new('$RUBOCOP_VERSION') >= Gem::Version.new('1.29')"`
        echo "::set-output name=markdown::$MARKDOWN"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      id: version
    - run: bundle exec rubocop --format github
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: bundle exec rubocop --format markdown -o rubocop.md
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      if: steps.version.outputs.markdown
    - run: cat rubocop.md >> $GITHUB_STEP_SUMMARY
      shell: bash
      if: always() && steps.version.outputs.markdown
      working-directory: ${{ inputs.working-directory }}
