name: Rubocop
description: Run Rubocop against a repository
author: Faculty Development Team

inputs:
  working-directory:
    description: Working directory for Gemfile
    required: false
    default: ./
  ruby-version:
    description: Sets the ruby version you want to build with.
    required: false
    default: 'default'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    - run: |
        RUBOCOP_VERSION=`bundle exec rubocop -v`
        MARKDOWN=`ruby -e "p Gem::Version.new('$RUBOCOP_VERSION') >= Gem::Version.new('1.29')"`
        echo "markdown=$MARKDOWN" >> $GITHUB_OUTPUT
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      id: version
    - run: bundle exec rubocop --format markdown >> $GITHUB_STEP_SUMMARY
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      if: ${{ steps.version.outputs.markdown == 'true' }}
    - run: bundle exec rubocop --format github
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      if: always()
