name: Check if CHANGELOG needs updating
description: Checks if files in lib/ have changed; if so, check if CHANGELOG.md has been updated
author: Workflow Improvement Team
inputs:
  changelog-file-path:
    description: Relative path to the CHANGELOG file
    required: false
    default: CHANGELOG.md

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Check if CHANGELOG needs updating
      run: |
        file_regex='^lib/|^bin/|^spec/|\.gemspec$'
        changes="$(git diff --name-only --diff-filter=ACMRT origin/main HEAD)"
        changelog_file="${{ inputs.changelog-file-path }}"
        echo "Changes relative to main branch:"
        echo "$changes"
        if [ -f "$changelog_file" ]
          echo "$changes" | grep -q -E "$file_regex" && \
          echo "$changes" | grep -Fqx "$changelog_file"
        else
          echo "No $changelog_file to update"
        fi
      shell: bash
