name: npm update
description: Run npm update and create a PR for any updates
author: Faculty Development Team

inputs:
  checkout-key:
    description: Key to use when checking out the repository
    required: true
  node-version:
    description: Version of node to use
    required: false
    default: '14'
  working-directory:
    description: Working directory for bundle update
    required: false
    default: ./

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ inputs.checkout-key }}
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: npm update
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        body: Changes after running `npm update`
        branch: npm-update
        commit-message: npm update
        delete-branch: true
        labels: dependencies, javascript
        title: npm update
