name: npm update
description: Run npm update and create a PR for any updates
author: Faculty Development Team

inputs:
  checkout-key:
    description: Key to use when checking out the repository
    required: true
  node-version:
    description: Version of node to use
    required: false
    default: '18'
  working-directory:
    description: Working directory for npm update
    required: false
    default: ./

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ inputs.checkout-key }}
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: ${{ inputs.working-directory }}
    - run: npm ci
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - id: outdated
      name: Get summary of outdated packages
      run: |
        SUMMARY=`npm outdated || true`
        DELIMITER="$(openssl rand -hex 8)"
        echo "summary<<${DELIMITER}" >> "${GITHUB_OUTPUT}"
        echo "${SUMMARY}" >> "${GITHUB_OUTPUT}"
        echo "${DELIMITER}" >> "${GITHUB_OUTPUT}"
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: npm update --save
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        body: |
          Changes after running `npm update --save`
          
          ### npm outdated summary
          ```
          ${{ steps.outdated.outputs.summary }}
          ```
        branch: npm-update
        commit-message: npm update
        delete-branch: true
        labels: dependencies, javascript
        title: npm update
        author: UoY Faculty Dev NPA <csrv1059@york.ac.uk>
