name: Bundle Update [development, test]
description: Run `bundle update --conservative` for non-production gems; create a PR for any updates; and set the PR to auto-merge
author: Faculty Development Team

inputs:
  checkout-key:
    description: Key to use when checking out the repository
    required: true
  container:
    description: Run in a container (don't run setup-ruby)
    required: false
    default: "false"
  github-token:
    description: GITHUB_TOKEN for setting the PR to auto merge
    required: true
  groups:
    description: Groups to ignore for production gems
    required: false
    default: "development:test"
  working-directory:
    description: Working directory for bundle update
    required: false
    default: ./

runs:
  using: composite
  steps:
    - uses: university-of-york/faculty-dev-actions/bundle-update-prep@v1
      with:
        checkout-key: ${{ inputs.checkout-key }}
        container: ${{ inputs.container }}
        working-directory: ${{ inputs.working-directory }}

    - run: bundle install
      if: ${{ inputs.container != 'false' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - run: bundle list --name-only > .gems-all
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - run: |
        export BUNDLE_WITHOUT=$BUNDLE_WITHOUT:${{ inputs.groups }}
        bundle list --name-only > .gems-prod
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - run: |
        cat .gems-all .gems-prod | sed '/No gems in the Gemfile/d' | sort | uniq -u > .gems-update
        cat .gems-update
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - run: xargs -a .gems-update bundle update --conservative
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - run: rm .gems-*
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v4
      with:
        body: Changes after running `bundle update --conservative` for non-production gems
        branch: bundle-update-dev
        commit-message: bundle update --conservative for non-production gems
        delete-branch: true
        labels: dependencies, ruby
        title: Bundle Update [non-production gems]
        author: UoY Faculty Dev NPA <csrv1059@york.ac.uk>

    - name: Enable auto-merge
      if: steps.cpr.outputs.pull-request-operation == 'created'
      run: gh pr merge "$PR_URL" --auto --delete-branch --squash
      shell: bash
      env:
        PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
