name: Cloudformation Deploy
description: Deploy to cloudformation
author: Faculty Development Team

inputs:
  aws-environment:
    description: AWS Environment (dev, staging, prod)
    required: true
  working-directory:
    description: Working directory for Gemfile
    required: false
    default: ./

permissions:
  contents: write

runs:
  using: composite
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 'default'
        bundler-cache: false
        working-directory: ${{ inputs.working-directory }}
    - name: Deploy via rake deploy task
      run: gem install rake && rake deploy:to['${{ inputs.aws-environment }}','github','GithubActionsDeploymentRole']
      shell: bash
      working-directory: ${{ inputs.working-directory }}
