name: Cloudformation Deploy
description: Deploy to cloudformation
author: Faculty Development Team

inputs:
  aws-environment:
    description: AWS Environment (dev, staging, prod)
    required: true

runs:
  using: composite
  steps:
    - name:
    - run: bundle exec rake deploy:to["${{ inputs.aws-environment }}", 'github']
      shell: bash
