name: rspec in Lambda with Github formatter
description: Run rspec within a lambda container and use the github formatter
author: Faculty Development Team

inputs:
  artifact-name:
    description: Name for the artifact to download (if required)
    required: false
    default: "false"
  artifact-path:
    description: Where to extract the artifact (if required)
    required: false
    default: public/js

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - run: bundle install --deployment --without development
      shell: bash
    - uses: actions/download-artifact@v4
      if: ${{ inputs.artifact-name != 'false' }}
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}
    - name: RSpec tests
      run: bundle exec rspec --format RSpec::Github::Formatter
      shell: bash
