name: Bundle Update Preparation
description: Preparations for running `bundle update`
author: Faculty Development Team

inputs:
  checkout-key:
    description: Key to use when checking out the repository
    required: true
  container:
    description: Run in a container (don't run setup-ruby)
    required: true
  working-directory:
    description: Working directory for bundle update
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ inputs.checkout-key }}
    - uses: ruby/setup-ruby@v1
      if: ${{ inputs.container == 'false' }}
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    # Fix for https://github.com/peter-evans/create-pull-request/issues/1170
    - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      shell: bash
    - run: bundle config --local deployment false
      if: ${{ inputs.container == 'false' }}
      shell: bash
      working-directory: ${{ inputs.working-directory }}
