name: rspec on Runner
description: Run rspec directly on a runner
author: Faculty Development Team

inputs:
  working-directory:
    description: Working directory for Gemfile
    required: false
    default: ./
  ruby-version:
    description: Sets the ruby version you want to build with.
    required: false
    default: 'default'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby-version }}
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    - run: bundle exec rspec
      shell: bash
      working-directory: ${{ inputs.working-directory }}
