name: rspec on Runner
description: Run rspec directly on a runner
author: Faculty Development Team

inputs:
  working-directory:
    description: Working directory for Gemfile
    required: false
    default: ./

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    - run: bundle exec rspec
      shell: bash
      working-directory: ${{ inputs.working-directory }}
