name: rspec in Lambda
description: Run rspec within a lambda container
author: Faculty Development Team

inputs:
  working-directory:
    description: Working directory for Gemfile
    required: false
    default: ./

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    - name: RSpec tests
      uses: docker://ghcr.io/university-of-york/faculty-dev-docker-images/ci/aws-lambda-ruby-postgres:2.7
      with:
        args: bundle exec rspec
