
name: Ruby container command
description: Run a command within our ruby container
inputs:
  command:
    description: Command to run
    required: true
  ruby-version:
    description: Ruby version to run, 3.2 or 2.7 currently
    required: true

runs:
  using: composite
  steps:
     # This step is here just because we can't use the
     # inputs data in an "image:" setting.
   - name: set ruby version
     id: ruby-ver
     runs-on: ubuntu-latest
     outputs:
       image: docker://ghcr.io/university-of-york/faculty-dev-docker-images/ci/aws-lambda-ruby-dev:${{ inputs.ruby-version }}

   - name: Run command
     image: ${{ steps.ruby-ver.outputs.image }}
     args:
      - bash
      - -c
      - ${{ inputs.command }}
