name: Bundle Update (on a runner)
description: Run bundle update on a runner and create a PR for any updates
author: Faculty Development Team

inputs:
  checkout-key:
    description: Key to use when checking out the repository
    required: true
  working-directory:
    description: Working directory for bundle update
    required: false
    default: ./

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ inputs.checkout-key }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        working-directory: ${{ inputs.working-directory }}
    - run: bundle config --local deployment false
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - run: bundle update
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        body: Changes after running `bundle update`
        branch: bundle-update
        commit-message: bundle update
        delete-branch: true
        labels: dependencies, ruby
        title: Bundle Update
