name: rspec in Lambda
description: Run rspec within a lambda container
author: Faculty Development Team

inputs:
  artifact-name:
    description: Name for the artifact to download (if required)
    required: false
    default: "false"
  artifact-path:
    description: Where to extract the artifact (if required)
    required: false
    default: public/js

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - run: bundle install --deployment --without development
      shell: bash
    - uses: actions/download-artifact@v4
      if: ${{ inputs.artifact-name != 'false' }}
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}
    - name: RSpec tests
      uses: docker://ghcr.io/university-of-york/faculty-dev-docker-images/ci/aws-lambda-ruby-postgres:2.7
      with:
        args: bundle exec rspec
