name: rspec in Lambda
description: Run rspec within a lambda container
author: Faculty Development Team

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - run: bundle install --deployment --without development
      shell: bash
    - name: RSpec tests
      uses: docker://ghcr.io/university-of-york/faculty-dev-docker-images/ci/aws-lambda-ruby-postgres:2.7
      with:
        args: bundle exec rspec
