name: rspec in Lambda
description: Run rspec within a lambda container
author: Faculty Development Team

inputs:
  db-user:
    description: Database user to use to connect to a postgres instance
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - run: bundle install --deployment --without development
      shell: bash
    - name: RSpec tests
      uses: docker://ghcr.io/university-of-york/faculty-dev-docker-images/ci/aws-lambda-ruby-postgres:2.7
      with:
        args: bundle exec rspec
      env:
        DB_HOST: postgres
        DB_USER: ${{ inputs.db-user }}
