name: rspec in Lambda
description: Run rspec within a lambda container
author: Faculty Development Team

inputs:
  artifact-name:
    description: Name for the artifact to download (if required)
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - run: bundle add rspec-github-actions-summary rspec-github
      shell: bash
    - run: bundle install --deployment --without development
      shell: bash
    - uses: actions/download-artifact@v3
      if: ${{ inputs.artifact-name != 'false' }}
      with:
        name: ${{ inputs.artifact-name }}
        path: public/js
    - name: RSpec tests
      run: bundle exec rspec --format RspecGithubActionsSummary --format RSpec::Github::Formatter
      shell: bash
    - run: bundle exec rspec-gh-summary >> $GITHUB_STEP_SUMMARY
      if: always()
      shell: bash
